
name: BinSkim

on:
  push:
    branches: [ master ]

jobs:
  lint:
    name: BinSkim
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.1.1

      - name: Get BinSkim package from nuget
        run: nuget install Microsoft.CodeAnalysis.BinSkim -Version 1.9.5 -OutputDirectory ${{ github.workspace }}

      - name: Run BinSkim analysis
        run: ${{ github.workspace }}\Microsoft.CodeAnalysis.BinSkim.1.9.5\tools\netcoreapp3.1\win-x64\BinSkim.exe analyze SubDir1\ --recurse -o result.sarif --force --ignorePdbLoadError

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: result.sarif
          path: result.sarif

      - name: Get Sarif Multitool package from nuget
        run: dotnet tool install --global Sarif.Multitool --version 3.1.0
      - name: Run Sarif Multitool
        run: sarif rebaseuri result.sarif --base-path-value ${{ github.workspace }} --base-path-token REPO -o result_rebased.sarif

      - name: upload 2
        uses: actions/upload-artifact@v3
        with:
          name: result_rebased.sarif
          path: result_rebased.sarif

      #- name: Upload SARIF file
      #  uses: github/codeql-action/upload-sarif@v2
      #  with:
      #    # Path to SARIF file relative to the root of the repository
      #    sarif_file: result.sarif
      #    # Optional category for the results
      #    # Used to differentiate multiple results for one commit
      #    category: binskim result